import Button from "~/components/Button";
import styles from "./index.module.css";
import Head from "next/head";
import Header from "~/components/Header";
import TextField from "~/components/TextField";
import { api } from "~/utils/api";
import Image from "next/image";
import background from '../assets/backgroundEncLink.svg'
import { useFormik, Form } from 'formik';

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const data = api.example.getAll.useQuery();
  
  const formik = useFormik({
    initialValues: {
      longLink: '',
    },
    onSubmit: values => {
      alert(JSON.stringify(values, null, 2));
    },
  });


  return (
    <>
      <Head>
        <title>PersonalizeLink | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Header />
        <div className={styles.container}>
          <form onSubmit={formik.handleSubmit} className={styles.contentForm}>
            <h1 className={styles.title}>Encurtador de link</h1>
            <p className={styles.text}>Crie grátis seu link de WhatsApp em instantes! Compartilhe no canais digitais para iniciar 
              conversas em apenas um clique.</p>
            <div className={styles.input}>
              <TextField 
              name="longLink" 
              label="*Seu link longo:" 
              placeholder="Cole o link aqui" 
              formik={formik} 
              />
            </div>
            <div className={styles.contentButton}>
            <Button text="Encurtar link" type="submit" />
            <Button text="Encurtar novo link" type="button" />
            </div>
          </form>
          <div className={styles.contentImage}>
            <Image className={styles.img} src={background} alt=""  />
            </div>
        </div>
      </div>
    </>
  );
}
